# Generated by Django 4.0.4 on 2022-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
