# Generated by Django 4.0.4 on 2022-05-05 11:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Soon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
    ]
