# Generated by Django 4.0.4 on 2022-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(choices=[('in stock', 'IN STOCK'), ('out of stock', 'OUT OF STOCK')], upload_to='images')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('delivery', models.CharField(choices=[('4 days delivery', '4 DAYS DELIVERY'), ('fast delivery', 'FAST DELIVERY')], default='fast delivery', max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
    ]
