# Generated by Django 4.0.4 on 2022-05-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_item_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
    ]
