# Generated by Django 4.0.4 on 2022-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.CharField(choices=[('in stock', 'IN STOCK'), ('out of stock', 'OUT OF STOCK')], default='in stock', max_length=30),
        ),
    ]
