# Generated by Django 4.0.4 on 2022-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0007_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('delivery', models.CharField(choices=[('4 days delivery', '4 DAYS DELIVERY'), ('fastdelivery', 'FASTDELIVERY')], default='fastdelivery', max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=1)),
                ('stock', models.CharField(choices=[('instock', 'IN STOCK'), ('outofstock', 'OUT OF STOCK')], default='instock', max_length=30)),
            ],
        ),
    ]
